---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/inframonit: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
      volumeClaimTemplate:
        spec:
          storageClassName: gp3-csi
          resources:
            requests:
              storage: 2Gi
    prometheusK8s:
      nodeSelector:
        node-role.kubernetes.io/inframonit: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
      volumeClaimTemplate:
        spec:
          storageClassName: gp3-csi
          resources:
            requests:
              storage: 50Gi
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/inframonit: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
    grafana:
      nodeSelector:
        node-role.kubernetes.io/inframonit: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/inframonit: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/inframonit: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/inframonit: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/inframonit: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/inframonit: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
