---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: inframonit
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - inframonit
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/inframonit: ""
  paused: false
