---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: recovery-cluster-reader
roleRef:
  name: cluster-reader
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: ocpreader
    apiGroup: rbac.authorization.k8s.io
