---
apiVersion: v1
kind: Service
metadata:
  name: internal-custom-nodeport
  namespace: openshift-ingress
  labels:
    app: router
    ingresscontroller.operator.openshift.io/owning-ingresscontroller: internal
spec:
  externalTrafficPolicy: Local
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: internal
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: https
  - name: metrics
    protocol: TCP
    nodePort: 31936
    port: 1936
    targetPort: 1936
  type: NodePort
