---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: internal
  namespace: openshift-ingress-operator
spec:
  httpHeaders:
    forwardedHeaderPolicy: IfNone
  replicas: 3
  domain: internal.domain.com
  endpointPublishingStrategy:
    loadBalancer:
      scope: Internal
    type: LoadBalancerService
  routeSelector:
    matchLabels:
      router: "internal"
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: "NoSchedule"
      key: node-role.kubernetes.io/infra
      operator: "Exists"
