---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
# MachineAutoScalers
  - machineautoscaler/compute-machineautoscaler.yaml
  - machineautoscaler/infra-machineautoscaler.yaml
  - machineautoscaler/inframonit-machineautoscaler.yaml
# MachineSets
  - machineset/infra-machineset.yaml
  - machineset/inframonit-machineset.yaml
  - machineset/compute-machineset.yaml
