---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Namespace
  - namespace/compliance.yaml
# OperatorGroup
  - operatorgroup/compliance.yaml
# Subscription
  - subscription/compliance.yaml
