---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - oauth/oauth.yaml
  - htpasswd/htpasswd-secret.yaml
  - htpasswd/ocpadmin-clusterrolebinding.yaml
  - htpasswd/ocpreader-clusterrolebinding.yaml
